using eShop.CoreBusiness.Models;
using eShop.UsesCases.PluginInterfaces.DataStore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eShop.DataStore.HardCoded
{
    public class ProductRepository : IProductRepository 
    {
        private List<Product> products;
        public ProductRepository()
        {
            products = new List<Product>
            {
               new Product{Id = 1 , Brand = "BSD", Name = "CUADRO BSD GRIME FRAME  FLAT BLACK", Description ="Toptube lengths 20.6 / 20.8 / 21 / 21.2 Headtube angle 75.5° Headtube length 117mm Seattube angle 71° Rear end length 12.8-13.2' BB Height 11.7' Standover height 9' Weight 5lbs Brake mounts none - brakeless Tubing Sanko Japanese seamless 4130 chromoly Colours Military Green / Raw / Black", LinkImage = "https://control.bicicletasmo.com.ar//images_prod/bsd-frame-grime-2021no1-flattransblack-001_1500x.jpg", Price="59900" },
               new Product{Id = 2, Brand = "FLY", Name = " FLYBIKES GEO color sig larry edgar", Description = "Tubing: Japanesse Seamless 4130 CrMo Headtube & Bottom Bracket: CNC machined 4130 CrMo heat treated Seat Clamp & Dropouts: Invest casting 4130 CrMo heat treated Stays bridges & Gussets: Laser cut 4130 CrMo heat treated Head tube: 74.5º (Larry model) Seat tube: 71º Rear end: 13.8 (Larry model) Standover: 9.25 BB height: 11.75 Top tube: 21 Headtube height: 113mm. / 4.45 Weight: 2.330g / 5.13lb ",LinkImage ="https://control.bicicletasmo.com.ar//images_prod/flybikes-2017-larry-edgar-geo-bmx-frame-metallic-burgundy-side.jpg", Price ="54900" },
               new Product{Id =3, Brand = "KINK", Name ="CUADRO KINK MUDRUNNER", Description= "SPEC Colors:Black ED, Matte Hunter Orange, Gloss Static Gray, Trans Black and Tan, Chad Osburn Signature Matte Trans CopperMaterial:100% Seamless Sanko 4130 Chromoly TubingHeadtube:Integrated Campy Spec with Updated Headtube BadgeDropouts:Investment Cast with Integrated Chain TensionersBottom Bracket:Internally and Externally Machined Mid Size BBBraking:Removable EBS Brake MountsParticulars:Internal Toptube and Downtube Gussets Widened Stays for Big Tire ClearanceWeight:4lb 6oz (20.5″)",LinkImage="https://control.bicicletasmo.com.ar//images_prod/frame_mudrunner_k6010-2075hor.jpg",Price="51900"},
               new Product{Id =4, Brand = "KROWBIKECO", Name =" CUADRO KROWBIKECO KREACIOM", Description= "SPEC Colors:Black ED, Matte Hunter Orange, Gloss Static Gray, Trans Black and Tan, Chad Osburn Signature Matte Trans CopperMaterial:100% Seamless Sanko 4130 Chromoly TubingHeadtube:Integrated Campy Spec with Updated Headtube BadgeDropouts:Investment Cast with Integrated Chain TensionersBottom Bracket:Internally and Externally Machined Mid Size BBBraking:Removable EBS Brake MountsParticulars:Internal Toptube and Downtube Gussets Widened Stays for Big Tire ClearanceWeight:4lb 6oz (20.5″)",LinkImage="https://control.bicicletasmo.com.ar//images_prod/frame_mudrunner_k6010-2075hor.jpg",Price="49900"},
               new Product{Id =5, Brand = "STRANGER", Name ="CUADRO STRANGER CRUX", Description="The Crux Frame is a no bells, no whistles entry level frame for younger riders. It features the same quick street style geometry as our high end Ballast frame with low cost frame construction technology.",LinkImage="https://control.bicicletasmo.com.ar//images_prod/stranger-crux-frame750_1024x1024.jpg",Price="59900"},
               new Product{Id =6, Brand = "BSD", Name ="HORQUILLA BSD ACID FORK black ed", Description= "Spec Offset: 22mm Weight: 2.2 lbs with steerer cap Colours: Black",LinkImage="https://control.bicicletasmo.com.ar//images_prod/bsd-forks-acidfork-black-002_1500x.jpg",Price="27000"},
               new Product{Id =7, Brand = " FLY", Name ="HORQUILLA FLY AGUA flat black", Description= "Offset: 32 mm Steer length: 155 mm Weight Black: 990 g / 2.18 lb (Top bolt included) Weight Flat Raw: 969 g / 2.13 lb (Top bolt include",LinkImage="https://control.bicicletasmo.com.ar//images_prod/fourche-flybikes-agua-32mm-flat-black.jpg",Price="28900"},
               new Product{Id =8, Brand = "KROW", Name ="HORQUILLA KROW BIG 341 cromada", Description= "nuevos ganchos 6mm espesor , top bolt M24, offset 25mm, vela CNC , full cromoly 4130, templado post welding",LinkImage="https://control.bicicletasmo.com.ar//images_prod/lgs_5897.jpg",Price="25000"},
               new Product{Id =9, Brand = "MISSION", Name ="HORQUILLA MISSION BMX BATTALION V2", Description= "PRODUCT SPECIFICATIONS MATERIAL: 100% 4130 Chromoly STEERER TUBE LENGTH: 165mm BEARING RACE: Integrated DROPOUT THICKNESS: 5mm DROPOUT SLOTS: (3/8) (10mm) OFFSET: 26mm COMPRESSION BOLT: M24x1.5mm Thread COMPRESSION BOLT: 6mm Allen Key FORK HEIGHT: 316mm WEIGHT: 42.0oz",LinkImage="https://control.bicicletasmo.com.ar//images_prod/forks_battalionv2_mn6502blk_1024x1024.jpg",Price="15900"},
               new Product{Id =10, Brand = "SHADOW", Name ="HORQUILLA SHADOW ODIN OFFSET 25MM", Description= "Esta horquilla fue producida utilizando las últimas innovaciones técnicas. El pivote de la horquilla no tiene líneas de corte ni tornillos internos para limitar la rotura. El diseño de este pivote aumenta la rigidez en los cojinetes de dirección. Las vainas están hidroformadas, lo que es más fuerte que una soldadura convencional. Se refinan en la parte inferior de la horquilla siempre en aras de la fuerza (cónica). A nivel de las patas de la horquilla, el proceso exclusivo de RigiDrop endurece y solidifica las bases. La principal ventaja de este sistema es que limita las grietas en las soldaduras. Compatible con clavijas en diámetros de 40 mm y neumáticos en 2.50 Disponible en 2 puertos (25 mm ) Peso: 898 grs. Color: negro",LinkImage="https://control.bicicletasmo.com.ar//images_prod/9649725da42ba4a624f7.70880865.jpg",Price="27900"},
               new Product{Id =11, Brand = "BSD", Name ="GRIPS BSD LEEZUS", Description= "The newest of new!! The Denim Cox signature Grime Grip features a traditional mushroom pattern in the super soft sticky Krayton rubber that you've come to expect from BSD. The design has reinforced slime at the ends for extra durability and a debossed Grime skull with missing teeth, just like Denim...",LinkImage="https://control.bicicletasmo.com.ar//images_prod/bsd-grip-grime-group-2021no3-001_900x900.jpg",Price="1700"},
               new Product{Id =12, Brand = " FLY", Name ="GRIPS FLYBIKES sig DEVON", Description= "Micro flanges 25º hardness compound (soft hardness) This item in black. Size: 160 x 29mm. Weight: 113 grs. / 3.98 oz. (pair)",LinkImage="https://control.bicicletasmo.com.ar//images_prod/images_8.jpg",Price="1900"},
               new Product{Id =13, Brand = "BSD", Name ="GRIPS BSD Dan Paley slims", Description= "Dan Paley Slims Grip Dan Paley is really fussy when it comes to grips, not too fat, not too thin, not too squishy, the list goes on. The Dan Paley Slims however are just right. Dan Paley Slims Grip Features: – Flangeless Dan Paley zigzag design – Krayton rubber – Bar ends included Spec Width: 160mm Diameter: 29mm installed Colours: Black Chocolate Sand Sur",LinkImage="https://control.bicicletasmo.com.ar//images_prod/bsd-grips-slims-group-2020colours-002_900x900.jpg",Price="1700"},
               new Product{Id =14, Brand = "CINEMA", Name ="GRIPS CINEMA INTERLACE", Description= "LENGTH 150mm DIAMETER 31mm BARENDS Expanding Type WEIGHT 4.8 oz",LinkImage="https://control.bicicletasmo.com.ar//images_prod/grips_interlace_cn6255blk_1800x1800.jpg",Price="1700"},
               new Product{Id =15, Brand = "BSD", Name ="GRIPS BSD LEEZUS", Description= "Pattern Flangeless distressed mushroom Length 160mm Diameter 29mm Material New softer stickier compound Bar Ends Forever bar ends with washers",LinkImage="https://control.bicicletasmo.com.ar//images_prod/bsd-grip-leezus-2021-004_1500x.jpg",Price="1700"},
               new Product{Id =16, Brand = "RANT", Name ="LLANTA RANT squad rim", Description= "The Squad Rim is a 36H double wall pinned rim that has been designed by Rant with shredders on a budget in mind. The exclusive design offers 4 separate chambers that increase strength and stiffness, while keeping weight down. - Double wall pinned construction - Extruded 6061 T6 alloy material - 16mm tall - 36mm wide - Weight 17.3 oz. / 490g - ERD: 392.8mm",LinkImage="https://control.bicicletasmo.com.ar//images_prod/bmx-rim-rant-squad-silver.jpg",Price="6000"},
               new Product{Id =17, Brand = "FLY", Name ="LLANTA FLY PIRAMIDE 2", Description= "6061-T6 Aluminum. Strong piramidal structure. Double wall construction. Anti-dent extra thick sidewalls. Pinch proof bottom rounded edges. Triple pinned to match welded strength at a more affordable price.",LinkImage="https://control.bicicletasmo.com.ar//images_prod/flybikes_piramide_rims.jpg",Price="5500"},
               new Product{Id =18, Brand = "DIVISION", Name ="LLANTA DIVISION city wide soldada", Description= "6061T6 alloy. Welded join. 36mm wide. 36 hole only. Black only. Weight: 487 Grams (1.07 lbs)",LinkImage="https://control.bicicletasmo.com.ar//images_prod/division-citywide-close3.jpg",Price="9500"},
               new Product{Id =19, Brand = "BSD", Name ="LLANTA BSD AERO RIM", Description= "The Aero Pro rim may look like a lightweight rim but don’t let it’s aerodynamic styling fool you. Like it’s big brother, the NASA rim, it’s design has been engineered with strength as the key feature. The Aero Pro rim has extra thick tapered sidewalls, angled spoke seats designed to accommodate proven cross-over lacing and a curved inner strut. It also has two intra cavity supports further increasing the radial stiffness and axial strength. The Aero Pro rim is constructed from space age 6066-T6 aluminium which is much stronger than the cheaper 6061 alloy traditionally used in most rims (+34% tensile strength vs 6061-T6). New chrome plated rim for 2019 - brake riders rejoice!! - Aero rim styling - Extra thick tapered sidewalls - Extra thick tapered spoke seats - Aligned cross over lacing - Curved inner strut - Can be used with brakes",LinkImage="https://control.bicicletasmo.com.ar//images_prod/bsd-rim-aeropro-black-001_1500x.jpg",Price="14900"},
               new Product{Id =20, Brand = "BSD", Name ="LLANTA BSD XLT", Description= "The XLT is our new lightweight rim, designed around an X-section for increased stiffness, the rim has an aero style shape which further triangulates the design. With other proven features such as tapered sidewalls and patented cross over lacing, the BSD XLT rim is built to handle serious abuse, If you’re trying to lighten your bike then rims and tires can make a big difference to how the bike handles due to the reduction of rotational mass. - Lightweight design - Extra thick tapered sidewalls - Extra thick tapered spoke seats - Aligned cross over lacing - X-section centre brace - Can be used with brakes - 34mm wide x 19mm tall - 6061-T6 construction",LinkImage="https://control.bicicletasmo.com.ar//images_prod/bsd-rim-xlt-2020no2-005_1500x.jpg",Price="13000"}

            };

        }

        public Product GetProduct(int id)=> products.FirstOrDefault(x => x.Id == id);
        

        public IEnumerable<Product> GetProducts(string filter = null)
        {
           if (string.IsNullOrEmpty(filter)) return products;
           return products.Where(x => x.Name.ToLower ().Contains(filter.ToLower()));
        }
    }
}
